version: "3.9"
services:
  api:
    build: ./backend
    container_name: urlshortener-api
    environment:
      PUBLIC_BASE: "http://localhost:8000"
      FRONTEND_ORIGIN: "http://localhost:5173"
      DATABASE_URL: "sqlite:///./dev.db"
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ./frontend
    container_name: urlshortener-web
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped
